### PR TITLE
Chessboard

### PR DESCRIPTION
**Pull request by WildoBro**
I have added the Pieces to the Chessboard. I included .SVG chess pieces to the assets/images folder.

### CODE REVIEW

**Comment by evan10003** [comment]
i will check this out if i have a chance tomorrow, if no one else has reviewed by then

**Comment by WildoBro** [comment]
Cool thanks, also my apologies, I accidentally sent you a request to review.

**Comment by evan10003** [comment]
no prob at all

**Comment by evan10003** [comment]
Looks great to me...one thing is i think king and queen need to be flipped? (queens at col 3 and kings at col 4).

**Pull request merged**
